version: "3"

services:
  pi-etcdkeeper:
    image: evildecay/etcdkeeper:v0.7.6
    container_name: pi-etcdkeeper
    environment:
      HOST: "0.0.0.0"
      PORT: 8088
    volumes:
      - ${DATA_PATH}/config/etcdkeeper-index.html:/opt/etcdkeeper/assets/etcdkeeper/index.html
    ports:
      - "8088:8088"
    restart: always

  pi-etcd:
    image: quay.io/coreos/etcd:v3.2.18
    container_name: pi-etcd
    command: etcd --data-dir /data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://pi-etcd:2379 --max-snapshots 5 --max-wals 5 --auto-compaction-retention=168
    volumes:
      - ${DATA_PATH}/etcd:/data
    ports:
      - "2379:2379"
    restart: always

  pi-mysql:
    image: mysql:5.7
    container_name: pi-mysql
    command: --max_allowed_packet=1073741824
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  pi-micro-api:
    image: micro/micro:v2.9.3
    container_name: pi-micro-api
    command: ["/micro", "--registry_address=pi-etcd:2379", "-registry=etcd", "api", "--handler=http"]
    ports:
      - "8080:8080"
    depends_on:
      - pi-etcd
    restart: always

  pi-micro-web:
    image: micro/micro:v2.9.3
    container_name: pi-micro-web
    command: ["/micro", "--registry_address=pi-etcd:2379", "-registry=etcd", "web"]
    ports:
      - "8082:8082"
    depends_on:
      - pi-etcd
    restart: always

  pi-redis:
    image: redis:5.0.7
    container_name: pi-redis
    command: redis-server
    environment: 
      - PORT=6379
    volumes:
      - ${DATA_PATH}/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ${DATA_PATH}/redis:/data
    ports:
      - "6379:6379"
    restart: always

  pi-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: pi-jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: always

  pi-zookeeper:
    image: zookeeper:latest
    container_name: pi-zookeeper
    ports:
      - "2181:2181"
    restart: always

  pi-kafka:
    image: wurstmeister/kafka:latest
    container_name: pi-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: pi-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    volumes:
      - ${DATA_PATH}/kafka:/kafka
    depends_on:
      - pi-zookeeper
    restart: always

  pi-kafka-manager:
    image: kafkamanager/kafka-manager:latest
    container_name: pi-kafka-manager
    environment:
      ZK_HOSTS: pi-zookeeper:2181
      KAFKA_BROKERS: pi-kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - pi-zookeeper
      - pi-kafka
    restart: always

  pi-rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: pi-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  pi-delay-queue:
    image: bitleak/lmstfy:latest
    container_name: pi-delay-queue
    ports:
      - "7777:7777"
      - "7778:7778"
    links:
      - pi-redis:redis
    depends_on:
      - pi-redis
    restart: always
